version: "3"
services:

  # Launch the db first
  dart_link_tailor_database:
    container_name: dart_link_tailor_database
    hostname: tailordb
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: myPassword123
      MYSQL_DATABASE: tailor
      MYSQL_USER: kerim
      MYSQL_PASSWORD: myPassword123

  # Launch this after
  dart_link_tailor_service:
    container_name: dart_tailor
    hostname: dartlt
    build:
      dockerfile: ./Dockerfile
      args:
        - DATABASE_URL=mysql://kerim:myPassword123@tailordb:3306/tailor
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_API_TOKEN=YOUR_API_TOKEN
      - HOST=dartlt
      - PORT=8080
      - LINK_TAILOR_RUN_MODE=debug
      - DATABASE_URL=mysql://kerim:myPassword123@tailordb:3306/tailor

networks:
  dart_tailor:
    external: true